# Generated by Django 5.2.9 on 2025-12-11 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnemyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("health", models.IntegerField()),
                ("speed", models.FloatField(help_text="Grid units per second")),
                (
                    "damage",
                    models.IntegerField(help_text="Damage to base if reaches end"),
                ),
                ("reward_coins", models.IntegerField(default=5)),
                ("reward_xp", models.IntegerField(default=10)),
                ("icon", models.CharField(default="👾", max_length=50)),
                (
                    "min_wave",
                    models.IntegerField(
                        default=1, help_text="First wave this enemy appears"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="buildingtype",
            name="category",
            field=models.CharField(
                choices=[
                    ("resource", "Resource Production"),
                    ("defense", "Defense Tower"),
                    ("special", "Special Building"),
                ],
                default="resource",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="buildingtype",
            name="min_level",
            field=models.IntegerField(default=1, help_text="Minimum level required"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="last_wave",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="waves_survived",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="buildingtype",
            name="production_rate",
            field=models.IntegerField(default=0, help_text="Resources per minute"),
        ),
        migrations.AlterField(
            model_name="buildingtype",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("coins", "Coins"),
                    ("wood", "Wood"),
                    ("stone", "Stone"),
                    ("food", "Food"),
                    ("none", "None"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Wave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wave_number", models.IntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("enemies_defeated", models.IntegerField(default=0)),
                ("total_enemies", models.IntegerField(default=0)),
                ("damage_taken", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waves",
                        to="game.playerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-wave_number"],
            },
        ),
        migrations.CreateModel(
            name="Enemy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_health", models.IntegerField()),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("is_alive", models.BooleanField(default=True)),
                ("spawn_time", models.DateTimeField(auto_now_add=True)),
                ("death_time", models.DateTimeField(blank=True, null=True)),
                (
                    "enemy_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.enemytype"
                    ),
                ),
                (
                    "wave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enemies",
                        to="game.wave",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeaponType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("base_damage", models.IntegerField(help_text="Base damage per shot")),
                ("base_range", models.IntegerField(help_text="Range in grid units")),
                ("base_fire_rate", models.FloatField(help_text="Shots per second")),
                ("cost_coins", models.IntegerField(default=0)),
                ("cost_wood", models.IntegerField(default=0)),
                ("cost_stone", models.IntegerField(default=0)),
                (
                    "min_level",
                    models.IntegerField(default=1, help_text="Minimum player level"),
                ),
                ("icon", models.CharField(default="🗼", max_length=50)),
                (
                    "upgrade_path",
                    models.ForeignKey(
                        blank=True,
                        help_text="What this upgrades to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upgrades_from",
                        to="game.weapontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_x", models.IntegerField()),
                ("position_y", models.IntegerField()),
                ("kills", models.IntegerField(default=0)),
                ("damage_dealt", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="towers",
                        to="game.playerprofile",
                    ),
                ),
                (
                    "weapon_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.weapontype",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "position_x", "position_y")},
            },
        ),
    ]
