# Generated by Django 5.2.9 on 2025-12-12 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_enemytype_buildingtype_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("production", "Production Worker"),
                            ("defense", "Defense Specialist"),
                            ("support", "Support Staff"),
                            ("elite", "Elite Worker"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cost_coins", models.IntegerField(default=50)),
                (
                    "cost_food",
                    models.IntegerField(default=10, help_text="Food cost per hire"),
                ),
                (
                    "upkeep_food",
                    models.IntegerField(default=1, help_text="Food consumed per day"),
                ),
                (
                    "production_multiplier",
                    models.FloatField(
                        default=1.0,
                        help_text="Production boost (1.0 = no boost, 1.5 = +50%)",
                    ),
                ),
                (
                    "damage_bonus",
                    models.IntegerField(default=0, help_text="Extra damage for towers"),
                ),
                (
                    "range_bonus",
                    models.IntegerField(default=0, help_text="Extra range for towers"),
                ),
                (
                    "fire_rate_multiplier",
                    models.FloatField(
                        default=1.0, help_text="Fire rate boost for towers"
                    ),
                ),
                (
                    "build_speed_multiplier",
                    models.FloatField(
                        default=1.0, help_text="Build speed boost (2.0 = 2x faster)"
                    ),
                ),
                (
                    "resource_efficiency",
                    models.FloatField(
                        default=1.0,
                        help_text="Resource usage efficiency (0.9 = -10% costs)",
                    ),
                ),
                (
                    "compatible_building_category",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank for all, or specify: resource/defense/special",
                        max_length=20,
                    ),
                ),
                ("min_level", models.IntegerField(default=1)),
                ("icon", models.CharField(default="👷", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="buildingtype",
            name="worker_capacity",
            field=models.IntegerField(
                default=2, help_text="Maximum workers that can be assigned"
            ),
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience", models.IntegerField(default=0)),
                (
                    "efficiency",
                    models.FloatField(
                        default=1.0,
                        help_text="Worker efficiency multiplier (improves with experience)",
                    ),
                ),
                (
                    "morale",
                    models.IntegerField(default=100, help_text="Worker morale (0-100)"),
                ),
                ("hired_at", models.DateTimeField(auto_now_add=True)),
                ("last_paid", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to="game.building",
                    ),
                ),
                (
                    "assigned_tower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to="game.tower",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to="game.playerprofile",
                    ),
                ),
                (
                    "worker_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.workertype",
                    ),
                ),
            ],
        ),
    ]
