# Generated by Django 5.2.9 on 2025-12-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_workertype_buildingtype_worker_capacity_worker"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("raw", "Raw Material"),
                            ("processed", "Processed Material"),
                            ("rare", "Rare Material"),
                            ("luxury", "Luxury Item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="📦", max_length=50)),
                (
                    "base_value",
                    models.IntegerField(
                        default=10, help_text="Base market value in coins"
                    ),
                ),
                ("is_tradeable", models.BooleanField(default=True)),
                (
                    "stack_size",
                    models.IntegerField(default=1000, help_text="Maximum stack size"),
                ),
                (
                    "produced_by_building",
                    models.CharField(
                        blank=True,
                        help_text="Building type name that produces this",
                        max_length=100,
                    ),
                ),
                (
                    "production_rate",
                    models.FloatField(
                        default=0, help_text="Base production per minute"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("agriculture", "Agriculture"),
                            ("mining", "Mining & Extraction"),
                            ("construction", "Construction"),
                            ("military", "Military"),
                            ("economy", "Economy"),
                            ("advanced", "Advanced Technology"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="🔬", max_length=50)),
                (
                    "research_time",
                    models.IntegerField(help_text="Research time in seconds"),
                ),
                ("cost_coins", models.IntegerField(default=0)),
                ("min_level", models.IntegerField(default=1)),
                (
                    "production_bonus",
                    models.FloatField(
                        default=0, help_text="Global production multiplier bonus"
                    ),
                ),
                (
                    "building_cost_reduction",
                    models.FloatField(
                        default=0, help_text="Building cost reduction (0.1 = -10%)"
                    ),
                ),
                (
                    "damage_bonus",
                    models.IntegerField(
                        default=0, help_text="Global tower damage bonus"
                    ),
                ),
                (
                    "unlock_building_type",
                    models.CharField(
                        blank=True,
                        help_text="Building type name to unlock",
                        max_length=100,
                    ),
                ),
                (
                    "unlock_worker_type",
                    models.CharField(
                        blank=True,
                        help_text="Worker type name to unlock",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prerequisite",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required technology",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocks",
                        to="game.technologytype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["category", "min_level"],
            },
        ),
        migrations.CreateModel(
            name="CraftingRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("furniture", "Furniture"),
                            ("decoration", "Decoration"),
                            ("equipment", "Equipment"),
                            ("tool", "Tool"),
                            ("consumable", "Consumable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="🔨", max_length=50)),
                (
                    "crafting_time",
                    models.IntegerField(help_text="Crafting time in seconds"),
                ),
                ("cost_coins", models.IntegerField(default=0)),
                (
                    "required_building",
                    models.CharField(
                        blank=True,
                        help_text="Building type name required for crafting",
                        max_length=100,
                    ),
                ),
                ("min_level", models.IntegerField(default=1)),
                (
                    "production_bonus",
                    models.FloatField(
                        default=0, help_text="Production boost for building"
                    ),
                ),
                (
                    "worker_capacity_bonus",
                    models.IntegerField(default=0, help_text="Extra worker slots"),
                ),
                (
                    "comfort_bonus",
                    models.IntegerField(default=0, help_text="Worker morale boost"),
                ),
                ("can_equip_to_building", models.BooleanField(default=True)),
                ("is_consumable", models.BooleanField(default=False)),
                ("tradeable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "required_technology",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technology required to unlock recipe",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.technologytype",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TradeOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_only",
                    models.BooleanField(
                        default=False, help_text="Only visible to party members"
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("material", "Material Trade"),
                            ("item", "Item Trade"),
                            ("mixed", "Mixed Trade"),
                        ],
                        max_length=20,
                    ),
                ),
                ("material_quantity", models.IntegerField(default=0)),
                ("item_quantity", models.IntegerField(default=0)),
                ("price_coins", models.IntegerField(default=0)),
                ("price_material_quantity", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Trade offer expiration"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for public listing",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_offers_received",
                        to="game.playerprofile",
                    ),
                ),
                (
                    "item_offered",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_in_trades",
                        to="game.craftingrecipe",
                    ),
                ),
                (
                    "material_offered",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_in_trades",
                        to="game.materialtype",
                    ),
                ),
                (
                    "price_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_as_currency",
                        to="game.materialtype",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_offers_sent",
                        to="game.playerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requirements",
                        to="game.craftingrecipe",
                    ),
                ),
                (
                    "material_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.materialtype",
                    ),
                ),
            ],
            options={
                "unique_together": {("recipe", "material_type")},
            },
        ),
        migrations.CreateModel(
            name="PlayerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "equipped_to_building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipped_items",
                        to="game.building",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="game.playerprofile",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.craftingrecipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("player", "recipe")},
            },
        ),
        migrations.CreateModel(
            name="PlayerMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "material_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.materialtype",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="game.playerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["material_type__category", "material_type__name"],
                "unique_together": {("player", "material_type")},
            },
        ),
        migrations.CreateModel(
            name="TechnologyMaterialRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "material_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.materialtype",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requirements",
                        to="game.technologytype",
                    ),
                ),
            ],
            options={
                "unique_together": {("technology", "material_type")},
            },
        ),
        migrations.CreateModel(
            name="PlayerTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("research_started", models.DateTimeField(auto_now_add=True)),
                ("research_completed", models.DateTimeField(blank=True, null=True)),
                ("is_researching", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="game.playerprofile",
                    ),
                ),
                (
                    "technology_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.technologytype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Player Technologies",
                "ordering": ["-research_started"],
                "unique_together": {("player", "technology_type")},
            },
        ),
    ]
