# Generated by Django 5.2.9 on 2025-12-13 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_materialtype_technologytype_craftingrecipe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tick_number", models.IntegerField(unique=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("players_processed", models.IntegerField(default=0)),
                ("buildings_completed", models.IntegerField(default=0)),
                ("researches_completed", models.IntegerField(default=0)),
                ("resources_collected", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-tick_number"],
            },
        ),
        migrations.AddField(
            model_name="buildingtype",
            name="storage_capacity",
            field=models.IntegerField(
                default=0, help_text="Material storage capacity bonus"
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="grid_size_x",
            field=models.IntegerField(default=10, help_text="Territory width"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="grid_size_y",
            field=models.IntegerField(default=10, help_text="Territory height"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="last_tick",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Last game tick processed"
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="material_storage_capacity",
            field=models.IntegerField(default=1000, help_text="Total material storage"),
        ),
        migrations.CreateModel(
            name="TerritorialExpansion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expansion_type",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal Expansion"),
                            ("vertical", "Vertical Expansion"),
                            ("both", "Full Expansion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cost_coins", models.IntegerField()),
                ("cost_wood", models.IntegerField(default=0)),
                ("cost_stone", models.IntegerField(default=0)),
                (
                    "size_increase",
                    models.IntegerField(default=2, help_text="Grid size increase"),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expansions",
                        to="game.playerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchased_at"],
            },
        ),
    ]
